[theme]
base = "light"
primaryColor = "#10B981"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111111"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
